print True and True ;print "1 Paul's Guess: True"
print False and True ;print "2 Paul's Guess: False"
print 1 == 1 and 2 ==1 ;print "3 Paul's Guess: False"
print "test" == "test" ;print "4 Paul's Guess: True"
print 1 == 1 or 2 != 1 ;print "5 Paul's Guess: True"
print True and 1 == 1 ;print "6 Paul's Guess: True"
print False and 0 != 0 ;print "7 Paul's Guess: False"
print True or 1 == 1 ;print "8 Paul's Guess: True"
print "test" == "testing" ;print "9 Paul's Guess: False"
print 1 != 0 and 2 == 1 ;print "10 Paul's Guess: False"
print "test" != "testing" ;print "11 Paul's Guess: True"
print "test" == 1 ;print "12 Paul's Guess: False"
print not (True and False) ;print "13 Paul's Guess: True"
print not (1 == 1 and 0 != 1) ;print "14 Paul's Guess: False"
print not (10 == 1 or 1000 == 1000) ;print "15 Paul's Guess: False"
print not (1 != 10 or 3 == 4) ;print "16 Paul's Guess: False"
print not ("testing" == "testing" and "Zed" == "Cool Guy") ;print "17 Paul's Guess: True"
print 1 == 1 and not ("testing" == 1 or 1 == 0) ;print "18 Paul's Guess: True"
print "chunky" == "bacon" and not (3 == 4 or 3 == 3) ;print "19 Paul's Guess: False"
print 3 == 3 and not ("testing" == "testing" or "Python" == "Fun") ;print "20 Paul's Guess: False"
